- name: "Check port {{ ansible_ssh_port }}"
  wait_for:
      port: "{{ ansible_ssh_port }}"
      state: "started"
      host: "{{ inventory_hostname }}"
      connect_timeout: "5"
      timeout: "5"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: ssh_port

- name: "Check port {{ fallback_ssh_port }}"
  wait_for:
      port: "{{ fallback_ssh_port }}"
      state: "started"
      host: "{{ inventory_hostname }}"
      connect_timeout: "5"
      timeout: "5"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: ssh_port_default
  when:
      - ssh_port is defined
      - ssh_port.state is undefined

- name: Set SSH port to the defined fallback
  set_fact:
      ansible_ssh_port: "{{ fallback_ssh_port }}"
  when: ssh_port_default.state is defined
